// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function DecodeBase64(arg1) {
  return window['go']['main']['App']['DecodeBase64'](arg1);
}

export function DecodeJWT(arg1, arg2) {
  return window['go']['main']['App']['DecodeJWT'](arg1, arg2);
}

export function EncodeBase64(arg1) {
  return window['go']['main']['App']['EncodeBase64'](arg1);
}

export function EncodeJWT(arg1, arg2) {
  return window['go']['main']['App']['EncodeJWT'](arg1, arg2);
}
