// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function HandleBase64() {
  return window['go']['main']['App']['HandleBase64']();
}

export function HandleBase64Decode(arg1) {
  return window['go']['main']['App']['HandleBase64Decode'](arg1);
}

export function HandleBase64Encode(arg1) {
  return window['go']['main']['App']['HandleBase64Encode'](arg1);
}

export function HandleCryptRSA() {
  return window['go']['main']['App']['HandleCryptRSA']();
}

export function HandleGreet() {
  return window['go']['main']['App']['HandleGreet']();
}

export function HandleHome() {
  return window['go']['main']['App']['HandleHome']();
}

export function HandleRSADecrypt(arg1, arg2) {
  return window['go']['main']['App']['HandleRSADecrypt'](arg1, arg2);
}

export function HandleRSAEncrypt(arg1, arg2) {
  return window['go']['main']['App']['HandleRSAEncrypt'](arg1, arg2);
}

export function HandleRSAGenerateKeyPair() {
  return window['go']['main']['App']['HandleRSAGenerateKeyPair']();
}
