// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function DecodeBase64(arg1:string):Promise<string>;

export function DecodeJWT(arg1:string,arg2:string):Promise<{[key: string]: any}>;

export function EncodeBase64(arg1:string):Promise<string>;

export function EncodeJWT(arg1:string,arg2:string):Promise<string>;
